kind: pipeline
name: Zaki

clone:
  depth: 1

steps:
- name: Building
  image: z4nyx/docker:latest
  environment:
    chat_id:
      from_secret: CHAT_ID
    token:
      from_secret: BOT_API_KEY
  commands:
  - git submodule update --init --recursive && bash build.sh
